"""Blender asset-catalog file parsing and the ST3E_Ext rewrite (Variant A).

A `blender_assets.cats.txt` line is `UUID:catalog/path:simple name`.
Every asset inside a .blend stores the catalog **UUID** (plus a cached simple
name for display). So renaming only the *path* and *simple name* while keeping
the UUID means the published .blend files need no edits at all - the assets
still resolve, they just appear under a differently-named tree.

That is the whole trick behind publishing `ST3E` as `ST3E_Ext`: the transform is
one text file, and the 66 .blend files are byte-identical copies.

bpy-free and pure - given the same input text you always get the same output.
"""

from __future__ import annotations

from typing import NamedTuple

VERSION_LINE = "VERSION 1"

DEFAULT_SIMPLE_NAME_SEPARATOR = "-"


class CatalogEntry(NamedTuple):
    uuid: str
    path: str
    simple_name: str


class CatalogFile(NamedTuple):
    """A parsed catalog file, preserving enough to round-trip it."""

    version: str
    entries: list          # list[CatalogEntry], in file order
    header_comments: list  # comment/blank lines seen before the VERSION line


class CatalogRewrite(NamedTuple):
    text: str              # the rewritten file content
    renamed: list          # list[(old_path, new_path)]
    unchanged: list        # catalog paths that matched no rename rule
    uuid_map: dict         # uuid -> (old_path, new_path) for every renamed entry


def parse(text: str) -> CatalogFile:
    """Parse catalog text. Tolerates comments, blank lines and a missing VERSION."""
    version = ""
    entries = []
    header_comments = []
    seen_version = False

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            if not seen_version:
                header_comments.append(raw_line.rstrip("\n"))
            continue
        if not seen_version and line.upper().startswith("VERSION"):
            version = line
            seen_version = True
            continue
        # Blender splits on the first two colons only: the simple name is free
        # text and the path may contain spaces and ampersands.
        parts = line.split(":", 2)
        if len(parts) != 3:
            continue
        uuid, path, simple = parts
        entries.append(CatalogEntry(uuid.strip(), path.strip(), simple.strip()))

    return CatalogFile(version or VERSION_LINE, entries, header_comments)


def simple_name_for(path: str, separator: str = DEFAULT_SIMPLE_NAME_SEPARATOR) -> str:
    """Blender's own convention: the catalog path with '/' swapped for '-'."""
    return path.replace("/", separator)


def apply_renames(path: str, rules: list) -> str:
    """Rewrite the leading component(s) of a catalog path.

    A rule matches when the path IS `from` or is nested under `from/`, so
    `ST3E` -> `ST3E_Ext` turns `ST3E/Deform` into `ST3E_Ext/Deform` while
    leaving an unrelated `Foo/ST3E` alone. The first matching rule wins, so
    rules never cascade into each other.
    """
    for rule in rules:
        src = (rule.get("from") or "").strip("/")
        dst = (rule.get("to") or "").strip("/")
        if not src or not dst:
            continue
        if path == src:
            return dst
        if path.startswith(src + "/"):
            return dst + path[len(src):]
    return path


def rewrite(
    text: str,
    rules: list,
    *,
    separator: str = DEFAULT_SIMPLE_NAME_SEPARATOR,
    stamp: str = "",
) -> CatalogRewrite:
    """Produce the published catalog text with paths + simple names renamed.

    UUIDs are carried across untouched - that is what keeps the published
    .blend files from needing a rewrite.
    """
    parsed = parse(text)

    renamed = []
    unchanged = []
    uuid_map = {}
    out_entries = []

    for entry in parsed.entries:
        new_path = apply_renames(entry.path, rules)
        if new_path == entry.path:
            unchanged.append(entry.path)
            out_entries.append(entry)
            continue
        new_entry = CatalogEntry(entry.uuid, new_path, simple_name_for(new_path, separator))
        out_entries.append(new_entry)
        renamed.append((entry.path, new_path))
        uuid_map[entry.uuid] = (entry.path, new_path)

    lines = []
    lines.append("# Blender Asset Catalog Definition file - PUBLISHED COPY.")
    lines.append("# Generated by LibraryPublisher. Do not edit here: edits are")
    lines.append("# overwritten on the next publish. Source of truth is the git repo.")
    if stamp:
        for stamp_line in stamp.splitlines():
            lines.append("# " + stamp_line)
    lines.append("#")
    lines.append("# Catalog paths are renamed on publish so this library sits")
    lines.append("# beside the local one in Blender's Asset Browser. UUIDs are")
    lines.append("# preserved, so the .blend files are untouched copies.")
    lines.append("")
    lines.append(parsed.version)
    lines.append("")
    for entry in out_entries:
        lines.append("%s:%s:%s" % (entry.uuid, entry.path, entry.simple_name))

    return CatalogRewrite("\n".join(lines) + "\n", renamed, unchanged, uuid_map)


def known_uuids(text: str) -> set:
    """Every catalog UUID defined in the file - used by the catalog_assigned check."""
    return {entry.uuid for entry in parse(text).entries}
