"""Write the icon gallery into ../README.md from out/manifest.json.

    python gallery.py

Plain Python, no Blender needed. Rewrites only the block between the
`<!-- icon-gallery:start -->` / `<!-- icon-gallery:end -->` markers, so run it
after build_icons.py whenever the roster changes.
"""
import html
import json
import os
from urllib.parse import quote

HERE = os.path.dirname(os.path.abspath(__file__))
README = os.path.join(os.path.dirname(HERE), "README.md")
MANIFEST = os.path.join(HERE, "out", "manifest.json")
START, END = "<!-- icon-gallery:start -->", "<!-- icon-gallery:end -->"

# Asset Browser catalog order, with the heading shown for each.
CATALOGS = [
    ("Deform", "ST3E/Deform"),
    ("Generate", "ST3E/Generate"),
    ("Modify", "ST3E/Modify"),
    ("Scatter", "ST3E/Scatter & Instancing"),
    ("Group", "ST3E/Group — node-editor helpers, not modifiers"),
    ("Shading", "ST3E/Shading — shader groups in `Blender/Shading/`"),
]
PER_ROW = 6
SIZE = 96


def cell(entry):
    png = os.path.basename(entry["png"])
    src = "_icons/out/" + quote(png)
    name = html.escape(entry["group"])
    return (f'<td align="center"><img src="{src}" width="{SIZE}" alt="{name}"><br>'
            f"<sub>{name}</sub></td>")


def gallery(entries):
    by_cat = {}
    for e in entries:
        by_cat.setdefault(e["catalog"], []).append(e)
    unknown = set(by_cat) - {c for c, _ in CATALOGS}
    if unknown:
        raise SystemExit(f"manifest has catalogs gallery.py does not know: {sorted(unknown)}")

    lines = [START, "",
             f"*{len(entries)} icons, generated by `_icons/gallery.py` from "
             "`_icons/out/manifest.json` — do not edit by hand.*", ""]
    for cat, heading in CATALOGS:
        items = sorted(by_cat.get(cat, []), key=lambda e: e["group"].lower())
        if not items:
            continue
        lines += [f"**{heading}** ({len(items)})", "", "<table>"]
        for i in range(0, len(items), PER_ROW):
            lines.append("<tr>" + "".join(cell(e) for e in items[i:i + PER_ROW]) + "</tr>")
        lines += ["</table>", ""]
    lines.append(END)
    return "\n".join(lines)


def main():
    with open(MANIFEST, encoding="utf-8") as f:
        entries = json.load(f)
    missing = [e["group"] for e in entries
               if not os.path.exists(os.path.join(HERE, "out", os.path.basename(e["png"])))]
    if missing:
        raise SystemExit(f"manifest lists icons with no PNG: {missing}")

    with open(README, encoding="utf-8") as f:
        text = f.read()
    if START not in text or END not in text:
        raise SystemExit(f"markers not found in {README}")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    with open(README, "w", encoding="utf-8", newline="\n") as f:
        f.write(head + gallery(entries) + tail)
    print(f"gallery: {len(entries)} icons written to {README}")


if __name__ == "__main__":
    main()
